### ISSUE TITLE
The received message is abnormal or the format is incorrect.

### ISSUE THREAD

**Issue by lzy-gogo** [nvlad/pushsharp.apple.http2#2]
![image](https://user-images.githubusercontent.com/83851147/117524066-6c5c5600-afee-11eb-9097-5c22e1e86ecf.png)

This error will occur in win7 system, but it can be pushed normally in win10 system. What causes it? What package does win7 need to install or upgrade to avoid this error?

**Comment by nvlad** [comment]
Windows before Win10 & Win2019 (Server) not support encryption used by APNS servers for SSL connections. Only upgrade OS resolve your problem.

**Comment by lzy-gogo** [comment]
> Windows before Win10 & Win2019 (Server) not support encryption used by APNS servers for SSL connections. Only upgrade OS resolve your problem.

ok thanks
